List carousel = [
  "assets/images/carousel/house1.jpg",
  "assets/images/carousel/house2.jpeg",
  "assets/images/carousel/house3.jpg",
  "assets/images/carousel/house4.jpg",
];

List categories = [
  "Living Room",
  "Bedroom",
  "Home Office",
  "Outdoor",
  "Kitchen",
  "Dining Room",
];

Map products = {
  1: {
    "product_name": "Sofa",
    "product_price": 1200,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 240], [125, 200, 112], [12, 25, 36],],
    "product_image": "assets/images/products/white_sofa.jpg",
    "product_model_android": "assets/models/Koltuk.glb",
    "product_model_ios": "assets/models/Koltuk.usdz",
    "category": "Living Room",
  },
  2: {
    "product_name": "Living Room Table",
    "product_price": 3580,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 25, 240], [125, 200, 11], [12, 25, 136],],
    "product_image": "assets/images/products/living_table.png",
    "product_model_android": "assets/models/modern_furniture.glb",
    "product_model_ios": "assets/models/Modern_Furniture.usdz",
    "category": "Living Room",
  },
  3: {
    "product_name": "Old Chair",
    "product_price": 250,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 240], [12, 125, 36],],
    "product_image": "assets/images/products/old_chair.png",
    "product_model_android": "assets/models/old_wooden_chair.glb",
    "product_model_ios": "assets/models/Old_Wooden_Chair.usdz",
    "category": "Outdoor",
  },
  4: {
    "product_name": "Modern Chair",
    "product_price": 580,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/modern_chair.png",
    "product_model_android": "assets/models/arm_chair__furniture.glb",
    "product_model_ios": "assets/models/Arm_chair__Furniture.usdz",
    "category": "Bedroom",
  },
  5: {
    "product_name": "Cyber Bed",
    "product_price": 5580,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/cyber_bed.png",
    "product_model_android": "assets/models/cyberpunk_bed__furniture.glb",
    "product_model_ios": "assets/models/Cyberpunk_Bed__furniture.usdz",
    "category": "Bedroom",
  },
  6: {
    "product_name": "Office Table",
    "product_price": 2880,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/office_table.png",
    "product_model_android": "assets/models/antique_wooden_table.glb",
    "product_model_ios": "assets/models/Antique_Wooden_Table.usdz",
    "category": "Home Office",
  },
  7: {
    "product_name": "Office Chair",
    "product_price": 1800,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/office_chair.png",
    "product_model_android": "assets/models/furniture-_modeling__texturing.glb",
    "product_model_ios": "assets/models/Furniture-_Modeling__Texturing.usdz",
    "category": "Home Office",
  },
  8: {
    "product_name": "Kitchen Table",
    "product_price": 820,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/kitchen_table.png",
    "product_model_android": "assets/models/coffeeshop_furniture_set.glb",
    "product_model_ios": "assets/models/Coffeeshop_Furniture_Set.usdz",
    "category": "Kitchen",
  },
  9: {
    "product_name": "Dining Table",
    "product_price": 2100,
    "product_description": "This is the product description attached to the product in the product description.",
    "product_colors": [[129, 255, 40], [125, 20, 112], [12, 25, 6],],
    "product_image": "assets/images/products/dining_table.png",
    "product_model_android": "assets/models/kitchen_furniture.glb",
    "product_model_ios": "assets/models/Kitchen_Furniture.usdz",
    "category": "Dining Room",
  },
};
